# Generated by Django 5.2.5 on 2025-08-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='novel_images/'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='narratives.authorprofile'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('personal', 'Personal Experience'), ('social', 'Social Issue')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='narratives.authorprofile'),
        ),
        migrations.CreateModel(
            name='Novella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='novella_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novellas', to='narratives.authorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShortStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='short_story_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_stories', to='narratives.authorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NovellaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('chapter_number', models.PositiveIntegerField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='novella_chapter_images/')),
                ('novella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='narratives.novella')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('novella', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='ShortStoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('part_number', models.PositiveIntegerField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='short_story_part_images/')),
                ('short_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='narratives.shortstory')),
            ],
            options={
                'ordering': ['part_number'],
                'unique_together': {('short_story', 'part_number')},
            },
        ),
    ]
